spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fulfillment
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/fulfillment
    user: postgres
    password: postgres
springdoc:
  swagger-ui:
    path: /fulfillment/swagger-ui.html
  api-docs:
    path: /fulfillment/api-docs
server:
  port: 8080
