create table products
(
    id int generated by default as identity primary key,
    product_id         varchar not null,
    status             varchar not null,
    fulfillment_center varchar not null,
    quantity           int              default 0,
    value              numeric not null default 0
);